import { Task } from "@/types/task";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing and deployment",
    status: "done",
    priority: "high",
    source: "code",
    assignee: "Alice",
    repo: "acme/dx-platform",
    dueDate: "2026-02-10",
    tags: ["devops", "infrastructure"],
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-01T14:30:00Z",
  },
  {
    id: "2",
    title: "Design system tokens",
    description: "Define color, spacing, and typography tokens for the design system",
    status: "in_progress",
    priority: "high",
    source: "cowork",
    assignee: "Bob",
    repo: "acme/design-system",
    dueDate: "2026-02-12",
    tags: ["design", "frontend"],
    createdAt: "2026-01-20T09:00:00Z",
    updatedAt: "2026-02-05T11:00:00Z",
  },
  {
    id: "3",
    title: "API rate limiting",
    description: "Implement rate limiting middleware for public API endpoints",
    status: "todo",
    priority: "urgent",
    source: "code",
    assignee: "Charlie",
    repo: "acme/api-gateway",
    dueDate: "2026-02-08",
    tags: ["backend", "security"],
    createdAt: "2026-01-25T08:00:00Z",
    updatedAt: "2026-01-25T08:00:00Z",
  },
  {
    id: "4",
    title: "User onboarding flow",
    description: "Create a step-by-step onboarding wizard for new users",
    status: "review",
    priority: "medium",
    source: "chat",
    assignee: "Diana",
    repo: "acme/web-app",
    dueDate: "2026-02-15",
    tags: ["frontend", "ux"],
    createdAt: "2026-01-18T12:00:00Z",
    updatedAt: "2026-02-06T16:00:00Z",
  },
  {
    id: "5",
    title: "Database migration script",
    description: "Write migration script for new user preferences schema",
    status: "todo",
    priority: "medium",
    source: "code",
    assignee: "Alice",
    repo: "acme/user-service",
    dueDate: "2026-02-14",
    tags: ["backend", "database"],
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "6",
    title: "Performance audit",
    description: "Run Lighthouse audits and fix critical performance issues",
    status: "in_progress",
    priority: "high",
    source: "cowork",
    assignee: "Bob",
    repo: "acme/web-app",
    dueDate: "2026-02-11",
    tags: ["frontend", "performance"],
    createdAt: "2026-01-28T14:00:00Z",
    updatedAt: "2026-02-07T09:00:00Z",
  },
  {
    id: "7",
    title: "Write E2E tests for auth",
    description: "Add Playwright tests for login, signup, and password reset flows",
    status: "todo",
    priority: "medium",
    source: "code",
    assignee: "Charlie",
    repo: "acme/web-app",
    dueDate: "2026-02-18",
    tags: ["testing", "qa"],
    createdAt: "2026-02-02T11:00:00Z",
    updatedAt: "2026-02-02T11:00:00Z",
  },
  {
    id: "8",
    title: "Notification system",
    description: "Implement in-app notifications with WebSocket support",
    status: "todo",
    priority: "low",
    source: "chat",
    assignee: "Diana",
    repo: "acme/notifications",
    dueDate: "2026-02-20",
    tags: ["fullstack", "feature"],
    createdAt: "2026-02-03T08:00:00Z",
    updatedAt: "2026-02-03T08:00:00Z",
  },
  {
    id: "9",
    title: "Dark mode support",
    description: "Add dark mode toggle with system preference detection",
    status: "review",
    priority: "low",
    source: "cowork",
    assignee: "Bob",
    repo: "acme/design-system",
    dueDate: "2026-02-13",
    tags: ["frontend", "design"],
    createdAt: "2026-01-22T15:00:00Z",
    updatedAt: "2026-02-06T10:00:00Z",
  },
  {
    id: "10",
    title: "API documentation",
    description: "Generate OpenAPI spec and interactive docs for all endpoints",
    status: "in_progress",
    priority: "medium",
    source: "chat",
    assignee: "Alice",
    repo: "acme/api-gateway",
    dueDate: "2026-02-16",
    tags: ["backend", "docs"],
    createdAt: "2026-02-04T09:00:00Z",
    updatedAt: "2026-02-07T14:00:00Z",
  },
];
